<?php

namespace IIAB\StudentTransferBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlottingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlottingRepository extends EntityRepository
{
}
