imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@IIABStudentTransferBundle/Resources/config/admin.yml" }
    - { resource: customer.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
            shared:
                driver: pdo_mysql
                host: '%shared_database_host%'
                port: '%shared_database_port%'
                dbname: '%shared_database_name%'
                user: '%shared_database_user%'
                password: '%shared_database_password%'
                charset: UTF8
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
            shared:
                connection: shared
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    lfSharedDataBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    port:           "465"
    encryption:     "ssl"
    auth_mode:      "login"

#JMS Translation Routing
jms_i18n_routing:
    default_locale: en
    locales: [en, es]
    strategy: prefix_except_default

#Sonata Block
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
        # Your other blocks

#Sonata Admin
sonata_admin:
    title: Transfer Admin
    title_logo: bundles/iiabstudenttransfer/images/stw-logo.png
    options:
        pager_links:  10
    templates:
        layout:  IIABStudentTransferBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    IIABStudentTransferBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [iiab.admin.left.side, iiab.admin.users]

            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [iiab.admin.right.side,iiab.admin.translations]
        groups:
            iiab.admin.left.side:
                label: iiab.admin.left.side
                label_catalogue: IIABStudentTransferBundle
                items: ~
                roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
            iiab.admin.right.side:
                label: iiab.admin.right.side
                label_catalogue: IIABStudentTransferBundle
                items: ~
                roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
            iiab.admin.right.users:
                label: iiab.admin.right.users
                label_catalogue: IIABStudentTransferBundle
                items: ~
                roles: [ROLE_ADMINROLE_SUPER_ADMIN]
            iiab.admin.translations:
                label: Translations
                items: ~
                roles: [ROLE_SUPER_ADMIN]
            iiab.admin.users:
                label: Users
                items: ~
                roles: [ROLE_SUPER_ADMIN]
##FOS Users
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: IIAB\StudentTransferBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: sonata.user.orm.user_manager

    from_email:
        address:        %mailer_user%
        sender_name:    TCS Specialty Application Website

ivory_ck_editor:
    base_path: "ckeditor/"
    js_path: "ckeditor/ckeditor.js"
    default_config: iiab
    configs:
      iiab:
        toolbar:                [ [ "Bold", "Italic", "Underline"], ["Dynamic", "Link"], ["Preview", "Source"] ]
